name: thesis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14.2
  - geopandas=1.1.2
  - pdal=2.9.3
  - scipy=1.16.1
  - tqdm=4.67.3
  - pip
  - pip:
      - pdal-plugins==1.6.6
      - tkintermapview==1.29